######################################################################
#
# File name : main_compile.do
# Created on: Fri Apr 19 17:12:34 -0500 2019
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
transcript off
onbreak {quit}
onerror {quit}

createdesign {project_1} {H:/Documents/5200Projects/project_1/project_1.sim/sim_1/behav/activehdl}
opendesign {H:/Documents/5200Projects/project_1/project_1.sim/sim_1/behav/activehdl/project_1/project_1.adf}
vlib work

vlib activehdl/xil_defaultlib
vdel -lib xil_defaultlib -all

null [set origin_dir "H:/Documents/5200Projects/project_1/project_1.sim/sim_1/behav/activehdl"]
null [set vlog_opts {}]
null [set vcom_opts {}]


eval vcom -93 $vcom_opts -work xil_defaultlib  \
	"$origin_dir/../../../../project_1.srcs/sources_1/new/ADD.vhd" \
	"$origin_dir/../../../../project_1.srcs/sources_1/new/ALU.vhd" \
	"$origin_dir/../../../../project_1.srcs/sources_1/new/CONTROL.vhd" \
	"$origin_dir/../../../../project_1.srcs/sources_1/new/INSTRMEM.vhd" \
	"$origin_dir/../../../../project_1.srcs/sources_1/new/MAINMEM.vhd" \
	"$origin_dir/../../../../project_1.srcs/sources_1/new/PCREG.vhd" \
	"$origin_dir/../../../../project_1.srcs/sources_1/new/REGFILE.vhd" \
	"$origin_dir/../../../../project_1.srcs/sources_1/new/REGMUX.vhd" \
	"$origin_dir/../../../../project_1.srcs/sources_1/new/SIGN1.vhd" \
	"$origin_dir/../../../../project_1.srcs/sources_1/new/SIGN2.vhd" \
	"$origin_dir/../../../../project_1.srcs/sources_1/new/main.vhd" \


quit
