######################################################################
#
# File name : main_simulate.do
# Created on: Fri Apr 19 17:13:20 -0500 2019
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
transcript off
opendesign H:/Documents/5200Projects/project_1/project_1.sim/sim_1/behav/activehdl/project_1/project_1.adf
set SIM_WORKING_FOLDER $dsn/..
asim -asdb +access +r +m+main -L secureip -L xil_defaultlib -O5 xil_defaultlib.main

if { ![batch_mode] } {
	wave *
} else {
	log *
}


run 10ps
if [batch_mode] {
	endsim
	quit
}
